pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                echo 'Checkout from GitHub'
                git branch: 'main', url: 'https://github.com/RakeshKasagani/Project_01_DependencyCheck_Docker.git'
            }
        }

        stage('Compile and Test') {
            steps {
                sh 'ls -ltr'
                sh 'cd java-cicd-project/spring-boot-app && mvn compile && mvn test'
            }
        }

        stage('SonarQube Scan') {
            steps {
                echo 'Running SonarQube analysis'
                sh '''
                cd java-cicd-project/spring-boot-app
                mvn sonar:sonar \
                  -Dsonar.host.url=http://3.95.175.98:9000 \
                  -Dsonar.login=sqa_8a0c3bd02f7b2139dacac2277f11d43cfa6f6d08
                '''
            }
        }

        stage('Dependency Check') {
            steps {
                script {
                    try {
                        sh '''
                        /opt/dependency-check/bin/dependency-check.sh \
                          --project "SpringBootApp" \
                          --scan java-cicd-project/spring-boot-app \
                          --format HTML \
                          --out dependency-check-report \
                          --data /opt/dc-data \
                          --noupdate
                        '''
                    } catch (Exception e) {
                        echo "Dependency Check failed, continuing pipeline..."
                    }
                }
            }
        }

        stage('Publish Report') {
            steps {
                script {
                    try {
                        publishHTML([
                            allowMissing: true,
                            alwaysLinkToLastBuild: true,
                            keepAll: true,
                            reportDir: 'dependency-check-report',
                            reportFiles: 'index.html',
                            reportName: 'OWASP Dependency-Check Report'
                        ])
                    } catch (Exception e) {
                        echo "Report not available"
                    }
                }
            }
        }

        stage('Build Application') {
            steps {
                sh 'cd java-cicd-project/spring-boot-app && mvn clean package'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'cd java-cicd-project/spring-boot-app && docker build -t rakesh268/java:${BUILD_NUMBER} .'
                }
            }
        }

        stage('Docker Image Scan') {
            steps {
                sh 'trivy image rakesh268/java:${BUILD_NUMBER}'
            }
        }

        stage('Push Image to Docker Hub') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'dockerhub', variable: 'DOCKER_PASS')]) {
                        sh '''
                        echo $DOCKER_PASS | docker login -u rakesh268 --password-stdin
                        docker push rakesh268/java:${BUILD_NUMBER}
                        '''
                    }
                }
            }
        }

        stage('Deploy Container') {
            steps {
                script {
                    sh '''
                    docker rm -f java-app || true
                    docker run -d -p 8000:8080 --name java-app rakesh268/java:${BUILD_NUMBER}
                    '''
                }
            }
        }
    }
}
