pipeline {
    agent any

    stages {
    stage('Checkout Code') {
        steps {
            echo 'scm git'
            git branch: 'main', url: 'https://github.com/RakeshKasagani/Project_01_DependencyCheck_Docker.git'
        }
    }
    
    
    stage('Compile and Test') {
      steps {
        sh 'ls -ltr'
        // build the project and create a JAR file
        sh 'cd java-cicd-project/spring-boot-app && mvn compile && mvn test'
      }
    }


    stage('sonar') {
    steps {
        echo 'scanning project'
        sh 'ls -ltr'
        sh '''cd java-cicd-project/spring-boot-app && mvn sonar:sonar \\
              -Dsonar.host.url=http://3.95.175.98:9000\\
              -Dsonar.login=sqa_8a0c3bd02f7b2139dacac2277f11d43cfa6f6d08'''
    }
}




stage('Dependency Check') {
    steps {
        sh '''
          /opt/dependency-check/bin/dependency-check.sh \
          --project "SpringBootApp" \
          --scan java-cicd-project/spring-boot-app \
          --format HTML \
          --data $WORKSPACE/odc-data \
          --out dependency-check-report
		  --nonupdate
        '''
    }
}


    stage('Publish Report') {
        steps {
            publishHTML([
                allowMissing: false,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'dependency-check-report',
                reportFiles: 'dependency-check-report.html',
                reportName: 'OWASP Dependency-Check Report'
            ])
        }
    }


    stage('Building the code') {
      steps {
        sh 'ls -ltr'
        // build the project and create a JAR file
        sh 'cd java-cicd-project/spring-boot-app && mvn clean package'
      }
    }

    stage('Build docker image'){
    steps{
        script{
            echo 'docker image build'
  sh 'cd java-cicd-project/spring-boot-app && docker build -t rakesh/java:${BUILD_NUMBER} .'
        }
    }
}
		
     stage('docker image scan'){
     steps{
         sh "trivy image rakesh/java:${BUILD_NUMBER}"
     }
 }		


stage('Push image to Hub'){
    steps{
        script{
            withCredentials([string(credentialsId: 'dockerhub', variable: 'dockerhub')]) {
            sh 'docker login -u rakesh268 -p ${dockerhub}'

      }
            sh 'docker push rakesh268/java:${BUILD_NUMBER}'
        }
    }
}


stage('Deploying image to docker container'){
    steps{
        script{
       
            sh 'docker run -itd --name java-app -p 8000:8080 rakesh/java:${BUILD_NUMBER}'
        }
    }
}

  }
}
