pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/RakeshKasagani/Project_01_DependencyCheck_Docker.git'
            }
        }

        stage('Compile and Test') {
            steps {
                sh 'cd java-cicd-project/spring-boot-app && mvn compile'
                sh 'cd java-cicd-project/spring-boot-app && mvn test'
            }
        }

        stage('Sonar Scan') {
            steps {
                sh '''
                cd java-cicd-project/spring-boot-app
                mvn sonar:sonar \
                -Dsonar.host.url=http://3.95.175.98:9000 \
                -Dsonar.login=sqa_8a0c3bd02f7b2139dacac2277f11d43cfa6f6d08
                '''
            }
        }

        stage('Dependency Check') {
            steps {
                script {
                    // DO NOT FAIL PIPELINE
                    sh '''
                    /opt/dependency-check/bin/dependency-check.sh \
                    --project "SpringBootApp" \
                    --scan java-cicd-project/spring-boot-app \
                    --format HTML \
                    --out dependency-check-report \
                    --data /opt/dc-data \
                    --noupdate || true
                    '''
                }
            }
        }

        stage('Publish Report') {
            steps {
                script {
                    // Run only if plugin installed
                    try {
                        publishHTML([
                            allowMissing: true,
                            alwaysLinkToLastBuild: true,
                            keepAll: true,
                            reportDir: 'dependency-check-report',
                            reportFiles: 'index.html',
                            reportName: 'OWASP Report'
                        ])
                    } catch (err) {
                        echo "HTML Publisher Plugin not installed, skipping report"
                    }
                }
            }
        }

        stage('Build Application') {
            steps {
                sh 'cd java-cicd-project/spring-boot-app && mvn clean package'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                cd java-cicd-project/spring-boot-app
                ls -ltr target
                docker build -t rakesh268/java:${BUILD_NUMBER} .
                '''
            }
        }

        stage('Docker Image Scan') {
            steps {
                sh 'trivy image rakesh268/java:${BUILD_NUMBER} || true'
            }
        }

        stage('Push Image to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub', variable: 'dockerhub')]) {
                    sh 'docker login -u rakesh268 -p ${dockerhub}'
                }
                sh 'docker push rakesh268/java:${BUILD_NUMBER}'
            }
        }

        stage('Deploy Container') {
            steps {
                sh '''
                docker rm -f java-app || true
                docker run -d -p 8000:8080 --name java-app rakesh268/java:${BUILD_NUMBER}
                '''
            }
        }
    }
}
